from pathlib import Path

path = Path("vehreg/catalog.py")
text = path.read_text(encoding="utf-8")

old = '''    def _add_trim(self, gen_id: str, raw: dict, source: str) -> None:\n        if not raw.get("name"):\n            raise CatalogError(f"{source}: trim under {gen_id} is missing name")\n        trim_id = f"{gen_id}.trim.{slug(raw.get('id') or raw['name'])}"\n        if trim_id in self.trims:\n            raise CatalogError(f"{source}: duplicate trim id {trim_id!r}")\n'''
new = '''    def _add_trim(self, gen_id: str, raw: dict, source: str) -> None:\n        if not raw.get("name"):\n            raise CatalogError(f"{source}: trim under {gen_id} is missing name")\n\n        # A MarketTrim is a real showroom SKU, not an unresolved analytical\n        # bucket. Its powertrain is part of the product identity and must be\n        # exact. UNKNOWN remains available to analytical Variants for source\n        # limitations, but it is not valid for a retail MarketTrim.\n        trim_powertrain = _facet(Powertrain, raw.get("powertrain"),\n                                 Powertrain.UNKNOWN)\n        if trim_powertrain is Powertrain.UNKNOWN:\n            raise CatalogError(\n                f"{source}: trim {raw['name']!r} under {gen_id} must declare "\n                "an exact powertrain")\n\n        # Explicit IDs stay stable. If omitted, powertrain participates in the\n        # generated identity so Premium BEV and Premium PHEV cannot collide.\n        raw_id = raw.get("id")\n        identity = raw_id or f"{raw['name']} {trim_powertrain.value}"\n        trim_id = f"{gen_id}.trim.{slug(identity)}"\n        if trim_id in self.trims:\n            raise CatalogError(f"{source}: duplicate trim id {trim_id!r}")\n'''
assert old in text, "MarketTrim loader anchor changed"
text = text.replace(old, new, 1)

old = '''            variant_id=variant_id,\n            powertrain=_facet(Powertrain, raw.get("powertrain"),\n                              Powertrain.UNKNOWN),\n            price_thb=raw.get("price_thb"),\n'''
new = '''            variant_id=variant_id,\n            powertrain=trim_powertrain,\n            price_thb=raw.get("price_thb"),\n'''
assert old in text, "MarketTrim powertrain constructor anchor changed"
text = text.replace(old, new, 1)

old = '''    def coverage(self) -> dict[str, int]:\n        scopes: dict[str, int] = {}\n'''
new = '''    def trim_coverage(self) -> dict[str, int]:\n        """Coverage counters for retail-product fields, separate from DLT grain.\n\n        Dimensions are canonical exterior length/width/height plus wheelbase,\n        all in millimetres. Missing dimensions stay missing rather than being\n        inherited or guessed from another trim.\n        """\n        dims = ("length_mm", "width_mm", "height_mm", "wheelbase_mm")\n        return {\n            "trims": len(self.trims),\n            "exact_powertrain": sum(\n                t.powertrain is not Powertrain.UNKNOWN for t in self.trims.values()),\n            **{name: sum(getattr(t, name) is not None for t in self.trims.values())\n               for name in dims},\n            "complete_dimensions": sum(\n                all(getattr(t, name) is not None for name in dims)\n                for t in self.trims.values()),\n        }\n\n    def coverage(self) -> dict[str, int]:\n        scopes: dict[str, int] = {}\n'''
assert old in text, "coverage anchor changed"
text = text.replace(old, new, 1)

old = '''                gen_payload: dict[str, Any] = {\n                    "code": gen.code, "segment": gen.segment.value,\n                    "seats": gen.seats, "launched": gen.launched,\n                    "ended": gen.ended, "variants": [],\n                }\n'''
new = '''                gen_payload: dict[str, Any] = {\n                    "code": gen.code, "segment": gen.segment.value,\n                    "seats": gen.seats, "launched": gen.launched,\n                    "ended": gen.ended, "variants": [], "trims": [],\n                }\n'''
assert old in text, "generation writer anchor changed"
text = text.replace(old, new, 1)

old = '''                    if variant.incomplete:\n                        variant_payload["incomplete"] = True\n                    gen_payload["variants"].append(variant_payload)\n                model_payload["generations"].append(gen_payload)\n'''
new = '''                    if variant.incomplete:\n                        variant_payload["incomplete"] = True\n                    gen_payload["variants"].append(variant_payload)\n\n                # Product data must survive every editor/save round-trip.\n                # Previously brand_payload() omitted trims completely.\n                for trim in self.trims_of_generation(gen.id):\n                    trim_payload = {\n                        "id": trim.id.split(".trim.", 1)[1],\n                        "name": trim.name,\n                        "variant_id": trim.variant_id,\n                        "powertrain": trim.powertrain.value,\n                        "price_thb": trim.price_thb,\n                        "drivetrain": trim.drivetrain.value,\n                        "engine_code": trim.engine_code,\n                        "engine_cc": trim.engine_cc,\n                        "battery_kwh": trim.battery_kwh,\n                        "transmission": trim.transmission,\n                        "seats": trim.seats,\n                        "length_mm": trim.length_mm,\n                        "width_mm": trim.width_mm,\n                        "height_mm": trim.height_mm,\n                        "wheelbase_mm": trim.wheelbase_mm,\n                        "tire_front": trim.tire_front,\n                        "tire_rear": trim.tire_rear,\n                        "wheel_front": trim.wheel_front,\n                        "wheel_rear": trim.wheel_rear,\n                        "aliases": list(trim.aliases),\n                        "source_refs": {\n                            source: list(refs)\n                            for source, refs in trim.source_refs.items()\n                        },\n                    }\n                    if trim.notes:\n                        trim_payload["notes"] = trim.notes\n                    gen_payload["trims"].append(trim_payload)\n                model_payload["generations"].append(gen_payload)\n'''
assert old in text, "brand_payload trim writer anchor changed"
text = text.replace(old, new, 1)

path.write_text(text, encoding="utf-8")
